workflows:
  ios_build:
    name: ClassGo iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Clean Flutter & SPM cache
        script: |
          flutter clean
          rm -rf ~/Library/Caches/org.swift.swiftpm/
          rm -rf ~/Library/Developer/Xcode/DerivedData/
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build iOS app
        script: flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphoneos/*.app
  
  android_build:
    name: ClassGo Android Build
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
